import type { CanonicalWord } from '../../domain/shared/words';
import { GENERATED_ACCEPTED_GUESSES } from './generated-accepted-guesses';

// Project-authored MVP curation. Keeping the source here makes the dictionary
// replaceable when a reviewed production word source is selected.
const ACCEPTED_GUESS_SOURCE = `
ABOUT ABOVE ABUSE ACTOR ACUTE ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT
ALIKE ALIVE ALLOW ALONE ALONG ALTER AMONG ANGER ANGLE ANGRY APART APPLE APPLY ARGUE ARISE ARRAY
ASIDE ASSET AUDIO AVOID AWARD AWARE BADLY BAKER BASIC BEACH BEGIN BEING BELOW BENCH BIRTH BLACK
BLAME BLIND BLOCK BLOOD BOARD BOOST BOOTH BOUND BRAIN BRAND BRAVE BREAK BREAD BRICK BRIEF BRING
BROAD BROKE BROWN BUILD BUILT BUYER CABLE CARRY CATCH CAUSE CHAIN CHAIR CHART CHASE CHEAP CHECK
CHEEK CHEST CHIEF CHILD CHOSE CIVIL CLAIM CLASS CLEAN CLEAR CLERK CLICK CLIMB CLOCK CLOSE CLOUD
COACH COAST COULD COUNT COURT COVER CRAFT CRASH CREAM CRIME CROSS CROWD CROWN CURVE CYCLE DAILY
DANCE DEALT DEATH DEBUT DELAY DEPTH DOING DOUBT DOZEN DRAFT DRAMA DREAM DRESS DRINK DRIVE EAGER
EARLY EARTH EIGHT EMPTY ENEMY ENJOY ENTER ENTRY EQUAL ERROR EVENT EVERY EXACT EXIST EXTRA FAITH
FALSE FAULT FAVOR FIELD FIFTH FIFTY FIGHT FINAL FIRST FIXED FLASH FLOOR FOCUS FORCE FORTH FORTY
FORUM FOUND FRAME FRESH FRONT FRUIT FUNNY GIANT GIVEN GLASS GLOBE GOING GRACE GRADE GRAND GRANT
GRASS GREAT GREEN GROSS GROUP GROWN GUARD GUESS GUEST GUIDE HAPPY HEART HEAVY HONEY HORSE HOTEL
HOUSE HUMAN IDEAL IMAGE INDEX INNER INPUT ISSUE JOINT JUDGE KNOWN LABEL LARGE LASER LATER LAUGH
LAYER LEARN LEAST LEAVE LEGAL LIGHT LIMIT LOCAL LOGIC LOOSE LOWER LUCKY LUNCH MAGIC MAJOR MAKER
MARCH MATCH MAYBE MAYOR METAL MIGHT MINOR MODEL MONEY MONTH MOTOR MOUNT MOUSE MOVIE MUSIC NEEDS
NEVER NEWLY NIGHT NOISE NORTH NOVEL NURSE OCCUR OFFER OFTEN ORDER OTHER OUGHT PAINT PANEL PAPER
PARTY PEACE PHASE PHONE PHOTO PIECE PILOT PITCH PLACE PLAIN PLANE PLANT PLATE POINT POUND POWER
PRESS PRICE PRIDE PRIME PRINT PRIOR PRIZE PROOF PROUD QUEEN QUICK QUIET RADIO RAISE RANGE RAPID
RATIO REACH READY REFER RIGHT RIVER ROUGH ROUND ROUTE ROYAL RURAL SCALE SCENE SCOPE SCORE SENSE
SERVE SEVEN SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT SHINE SHOCK SHOOT SHORT SHOWN SIGHT SINCE
SKILL SLEEP SLIDE SMALL SMART SMILE SOLID SOLVE SORRY SOUND SOUTH SPACE SPARE SPEAK SPEED SPEND
SPENT SPLIT SPORT STAFF STAGE STAKE STAND START STATE STEAM STEEL STICK STILL STOCK STONE STOOD
STORE STORM STORY STRIP STUCK STUDY STUFF STYLE SUGAR TABLE TAKEN TASTE TEACH TEETH THEIR THEME
THERE THESE THING THINK THIRD THOSE THREE THREW THROW TIGHT TIMES TIRED TITLE TODAY TOPIC TOTAL
TOUCH TOUGH TOWER TRACK TRADE TRAIN TREAT TREND TRIAL TRUCK TRULY TRUST TRUTH TWICE UNDER UNION
UNITY UNTIL UPPER UPSET URBAN USAGE USUAL VALID VALUE VIDEO VISIT VITAL VOICE WASTE WATCH WATER
WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WITCH WOMAN WOMEN WORLD WORRY WORSE WORST WORTH WOULD
WRITE WRONG WROTE YOUNG
`;

export const ACCEPTED_GUESSES: readonly string[] = Object.freeze(
  [...new Set([
    ...GENERATED_ACCEPTED_GUESSES,
    ...ACCEPTED_GUESS_SOURCE.trim().split(/\s+/),
  ])].sort(),
);

const ACCEPTED_GUESS_SET = new Set(ACCEPTED_GUESSES);

export interface DailyDictionary {
  readonly size: number;
  accepts(word: CanonicalWord): boolean;
}

export const dailyDictionary: DailyDictionary = Object.freeze({
  size: ACCEPTED_GUESSES.length,
  accepts: (word: CanonicalWord) => ACCEPTED_GUESS_SET.has(word),
});

export function isAcceptedDailyGuess(value: unknown): value is string {
  return typeof value === 'string' && ACCEPTED_GUESS_SET.has(value.toUpperCase());
}
