// Project-authored answer curation. Targets are deliberately separated from
// accepted guesses so unusual valid guesses never become answers by accident.
const TARGET_WORD_SOURCE = `
ABOUT ABOVE ACTOR ACUTE ADULT AFTER AGAIN AGENT AHEAD ALARM ALBUM ALERT ALIVE ALONE ALONG ALTER
AMONG ANGER ANGLE ANGRY APART APPLE ARGUE ARISE ASIDE AUDIO AVOID AWARD AWARE BAKER BASIC BEACH
BEGIN BELOW BENCH BIRTH BLACK BLAME BLIND BLOCK BLOOD BOARD BRAIN BRAND BRAVE BREAK BREAD BRICK
BRIEF BRING BROAD BROWN BUILD CABLE CARRY CATCH CAUSE CHAIN CHAIR CHART CHASE CHEAP CHECK CHEST
CHIEF CHILD CIVIL CLAIM CLASS CLEAN CLEAR CLIMB CLOCK CLOSE CLOUD COACH COAST COUNT COURT COVER
CRAFT CRASH CREAM CRIME CROSS CROWD CROWN DAILY DANCE DEATH DELAY DEPTH DOUBT DOZEN DRAFT DRAMA
DREAM DRESS DRINK DRIVE EAGER EARLY EARTH EIGHT EMPTY ENJOY ENTRY EQUAL EVENT EXACT EXTRA FAITH
FALSE FAULT FIELD FIGHT FINAL FIRST FLASH FLOOR FOCUS FORCE FOUND FRAME FRESH FRONT FRUIT FUNNY
GIANT GIVEN GLASS GLOBE GRACE GRADE GRAND GRASS GREAT GREEN GROUP GROWN GUARD GUEST GUIDE HAPPY
HEART HEAVY HONEY HORSE HOTEL HOUSE HUMAN IDEAL IMAGE INDEX INNER JOINT JUDGE KNOWN LABEL LARGE
LASER LATER LAUGH LAYER LEARN LEAST LEAVE LEGAL LIGHT LIMIT LOCAL LOGIC LUCKY LUNCH MAGIC MAJOR
MAKER MARCH MATCH MAYBE METAL MODEL MONEY MONTH MOTOR MOUNT MOUSE MOVIE MUSIC NEVER NIGHT NOISE
NORTH NOVEL NURSE OFFER OFTEN ORDER OTHER PAINT PANEL PAPER PARTY PEACE PHASE PHONE PHOTO PIECE
PILOT PITCH PLACE PLAIN PLANE PLANT PLATE POINT POUND POWER PRICE PRIDE PRIME PRINT PRIZE PROOF
PROUD QUEEN QUICK QUIET RADIO RAISE RANGE RAPID RATIO REACH READY RIGHT RIVER ROUGH ROUND ROUTE
ROYAL RURAL SCALE SCENE SCOPE SCORE SENSE SERVE SEVEN SHAPE SHARE SHARP SHEET SHELF SHELL SHIFT
SHINE SHOCK SHOOT SHORT SIGHT SKILL SLEEP SLIDE SMALL SMART SMILE SOLID SOLVE SOUND SOUTH SPACE
SPARE SPEAK SPEED SPEND SPLIT SPORT STAGE STAKE STAND START STATE STEAM STEEL STICK STILL STOCK
STONE STORE STORM STORY STRIP STUDY STUFF STYLE SUGAR TABLE TASTE TEACH TEETH THEME THERE THESE
THING THINK THIRD THREE THROW TIGHT TIRED TITLE TODAY TOPIC TOTAL TOUCH TOUGH TOWER TRACK TRADE
TRAIN TREAT TREND TRIAL TRUCK TRUST TRUTH TWICE UNDER UNION UNITY UNTIL UPPER UPSET URBAN USAGE
USUAL VALID VALUE VIDEO VISIT VITAL VOICE WASTE WATCH WATER WHEEL WHERE WHICH WHILE WHITE WHOLE
WITCH WOMAN WORLD WORRY WORSE WORTH WOULD WRITE WRONG YOUNG
`;

export const TARGET_WORDS: readonly string[] = Object.freeze(
  [...new Set(TARGET_WORD_SOURCE.trim().split(/\s+/))],
);
